# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
   include:
   - feature/test

   exclude:
   - main
   - feature/dev

 batch: true

stages:
- stage: 'CI'
  jobs:
  - job: 'Buildjob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      name: 'release'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: 'cc6c5f41-bf3b-4a38-b0fb-b5b6523620f8'
    
    - task: DotNetCoreCLI@2
      name: 'build'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '-c $(buildconfig)'
    
    - task: DotNetCoreCLI@2
      name: 'publish'
      inputs:
        command: publish
        projects: '**/*csproj'
        arguments: '-c $(buildConfig) -o $(build.stagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      name: 'publishArtifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'box'
        publishLocation: 'Container'
        StoreAsTar: true

# - stage: 'CD'
#   jobs:
#   - job: 'deployToTest'
#     pool:
#       vmImage: 'ubuntu-latest'
#     steps:
#     - task: DownloadBuildArtifacts@1
      



