# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - feature/test 

variables:
  projectName: '**/*.csproj'
  buildConfig: 'debug'

pool:
  vmImage: windows-latest

stages:
- stage: CI
  jobs:
  - job: 'buildJob'
    displayName: 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'restore'
      inputs:
        command: restore
        projects: '$(projectName)'
    
    - task: DotNetCoreCLI@2
      displayName: 'build'
      inputs:
        command: build
        projects: '$(projectName)'
        arguments: '-c $(buildConfig)'
    
    - task: DotNetCoreCLI@2
      displayName: 'publish'
      inputs:
        command: publish
        projects: '$(projectName)'
        arguments: '-c $(buildConfig) -o $(build.stagingDirectory)'
    
    - task: PublishPipelineArtifact@1
      displayName: 'publish Artifact'
      inputs:
        targetPath: '$(build.stagingDirectory)'
        artifact: 'depo'
        publishLocation: pipeline
        

- stage: CD
  dependsOn: CI
  jobs:
  - deployment: 'deployToVmJob'
    environment: 
      name: myRevisitpools
      resourceType: virtualmachine
    
    strategy:
      runOnce:
        deploy:
          steps:

          # - task: IISWebAppManagementOnMachineGroup@0
          #   inputs:
          #     EnableIIS: true
          #     IISDeploymentType: 'IISWebsite'
          #     ActionIISWebsite: 'CreateOrUpdateWebsite'
          #     WebsiteName: 'Default Web Site'
          #     WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
          #     WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
          #     AddBinding: true
          #     Bindings: '{"bindings": [{"protocol": "http","ipAddress": "All Unassigned","port": "80","hostname":"calculator.com","sslThumbprint": "","sniFlag": false}]}'
              
          - powershell: |
              Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/4956ec5e-8502-4454-8f28-40239428820f/e7181890eed8dfa11cefbf817c4e86b0/dotnet-hosting-8.0.11-win.exe" -outfile $env:temp\DotNetCore.WindowsHosting.exe
              Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(pipeline.workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true