# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - feature/test 

variables:
  projectName: '**/*.csproj'
  buildConfig: 'debug'

pool:
  vmImage: windows-latest

stages:
- stage: CI
  jobs:
  - job: 'buildJob'
    displayName: 
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'restore'
      inputs:
        command: restore
        projects: '$(projectName)'
    
    - task: DotNetCoreCLI@2
      displayName: 'build'
      inputs:
        command: build
        projects: '$(projectName)'
        arguments: '-c $(buildConfig)'
    
    - task: DotNetCoreCLI@2
      displayName: 'publish'
      inputs:
        command: publish
        projects: '$(projectName)'
        arguments: '-c $(buildConfig) -o $(build.stagingDirectory)'
    
    - task: PublishPipelineArtifact@1
      displayName: 'publish Artifact'
      inputs:
        targetPath: '$(build.stagingDirectory)'
        artifact: 'depo'
        publishLocation: pipeline
        
      
