# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none



##CI stage
stages:
- stage: 'CI'
  jobs:
  - job: 'Buildjob'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      name: 'release'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
        vstsFeed: 'cc6c5f41-bf3b-4a38-b0fb-b5b6523620f8'
    
    - task: DotNetCoreCLI@2
      name: 'build'
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '-c $(buildconfig)'
    
    - task: DotNetCoreCLI@2
      name: 'publish'
      inputs:
        command: publish
        projects: '**/*csproj'
        arguments: '-c $(buildConfig) -o $(build.stagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      name: 'publishArtifact'
      inputs:
        PathtoPublish: '$(build.stagingDirectory)'
        ArtifactName: 'box'
        publishLocation: 'Container'
        StoreAsTar: true



##CD stage
- stage: 'CD'
  jobs:
  - job: 'deployToTest'     ##deploy to TEST env
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1      #Download Artifact using Download Build Artifact 
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'box'
        downloadPath: '$(build.stagingDirectory)'

    - task: AzureRmWebAppDeployment@4     #Deploy to Azure Web App - TEST
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(1)(52ebb814-d1d8-427b-badb-92e9e2108392)'
        appType: 'webApp'
        WebAppName: 'revisitapp-test'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'





  - job: 'deployToDev'        ##deploy to DEV env
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2        #Download Artifact using Pipeline Artifact
      inputs:
        buildType: 'current'
        artifactName: 'box'

    - task: AzureRmWebAppDeployment@4       #Deploy to Azure Web App - DEV
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(1)(52ebb814-d1d8-427b-badb-92e9e2108392)'
        appType: 'webApp'
        WebAppName: 'revisitapp-dev'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'



  - job: 'deployToProd'     ##deploy to PROD env
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: 'current'           #Download Artifact using Pipeline Artifact
      artifact: 'box'

    - task: AzureRmWebAppDeployment@4               #Deploy to Azure Web App - PROD
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go(1)(52ebb814-d1d8-427b-badb-92e9e2108392)'
        appType: 'webApp'
        WebAppName: 'revisitapp-prod'
        deployToSlotOrASE: true
        ResourceGroupName: 'revisit-rg'
        SlotName: 'revisitapp-prod-staging'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'