# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
  buildConfig: 'xyz'

pool:
  vmImage: windows-latest

stages:
- stage: CI
  jobs:
  - job: buildjob
    steps:
    - task: DotNetCoreCLI@2
      displayName: restoretask
      inputs:
        command: 'restore'
        projects: '$(projectName)'
        feedsToUse: 'select'
    
    - task: DotNetCoreCLI@2
      displayName: buildtask
      inputs:
        command: 'build'
        projects: '$(projectName)'
        arguments: '-c ${{parameters.buildConfig}}'
    
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: $(projectName)
        publishWebProjects: true
        arguments: '-c ${{parameters.buildConfig}} -o $(build.stagingDirectory)'