#parent multistaging pipeline

trigger:
    branches:
        include:
        - main
        - feature/*
    batch: true
pool:
    vmImage: windows-latest

stages:

##CI Stage
- stage: CI             
  displayName: StageCI
  jobs:
    - job: buildJob
      steps:
      - template: revisit233-buildp.yml     #calling build yaml file as child pipeline with repository as 'debug'
        parameters:
            buildConfig: 'debug'
    
      - template: revisit233-buildp.yml
        parameters:
            buildConfig: 'backup'       #calling build yaml file as child pipeline with repository as 'debug2'

      - task: PublishBuildArtifacts@1
        displayName: publish artifact task
        inputs:
          PathtoPublish: '$(build.stagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'


- stage: TEST
  displayName: TEST
  dependsOn: CI
  condition: contains(variables['Build.SourceBranch'],'refs/heads/feature/test')
  jobs:
  - deployment: deployToTest
    displayName: 'TestEnv'
    environment: 
      name: 'MymultiPools'
      resourceType: Virtualmachine
      tags: test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: IIS setup
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'Default Web Site'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings": [{"protocol": "http","ipAddress": "All Unassigned","port": "80","hostname":"calculator.com","sslThumbprint": "","sniFlag": false}]}'
              
          - powershell: |
              Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/4956ec5e-8502-4454-8f28-40239428820f/e7181890eed8dfa11cefbf817c4e86b0/dotnet-hosting-8.0.11-win.exe" -outfile $env:temp\DotNetCore.WindowsHosting.exe
              Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'website deployed in IIS'
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(pipeline.workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true


- stage: DEV
  dependsOn: TEST
  displayName: DEV
  condition: contains(variables['Build.SourceBranch'],'refs/heads/feature/dev')
  jobs:
  - deployment: deployToDev
    displayName: 'DevEnv'
    environment:
      name: 'MymultiPools'
      resourceType: virtualmachine
      tags: test
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: IIS setup
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'Default Web Site'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings": [{"protocol": "http","ipAddress": "All Unassigned","port": "80","hostname":"calculator.com","sslThumbprint": "","sniFlag": false}]}'
              
          - powershell: |
              Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/4956ec5e-8502-4454-8f28-40239428820f/e7181890eed8dfa11cefbf817c4e86b0/dotnet-hosting-8.0.11-win.exe" -outfile $env:temp\DotNetCore.WindowsHosting.exe
              Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'website deployed in IIS'
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(pipeline.workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true


- stage: PROD
  displayName: PROD
  dependsOn: DEV
  condition: contains(variables['Build.SourceBranch'],'refs/heads/main')
  jobs:
  - deployment: deployToProd
    displayName: 'ProdEnv'
    environment:
      name: MymultiPools
      resourceType: virtualmachine
      tags: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            displayName: IIS setup
            inputs:
              EnableIIS: true
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'Default Web Site'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: '{"bindings": [{"protocol": "http","ipAddress": "All Unassigned","port": "80","hostname":"calculator.com","sslThumbprint": "","sniFlag": false}]}'
              
          - powershell: |
              Invoke-WebRequest "https://download.visualstudio.microsoft.com/download/pr/4956ec5e-8502-4454-8f28-40239428820f/e7181890eed8dfa11cefbf817c4e86b0/dotnet-hosting-8.0.11-win.exe" -outfile $env:temp\DotNetCore.WindowsHosting.exe
              Start-Process $env:temp\DotNetCore.WindowsHosting.exe -ArgumentList '/quiet' -Wait
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            displayName: 'website deployed in IIS' 
            inputs:
              WebSiteName: 'Default Web Site'
              Package: '$(pipeline.workspace)\**\*.zip'
              TakeAppOfflineFlag: true
              XmlVariableSubstitution: true


